config/routes.rb
Sfs::Application.routes.draw do
  get "welcome/index"

  resources :themes

  resources :subthemes

  resources :words

  resources :languages

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :description, :language_id, :subtheme_id, :theme_id, :url, :word_id

  validates :url, :uniqueness => true
  
  belongs_to :language
  belongs_to :theme
  belongs_to :subtheme
  belongs_to :word
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :description, :name_original, :name

  validates :name, :uniqueness => true
  has_many :themes
  has_many :words, :through => :themes
  has_many :documents
end

app/models/subtheme.rb
class Subtheme < ActiveRecord::Base
  attr_accessible :description, :image, :name, :theme_id, :video_url

  validates :name, :uniqueness => true
  belongs_to :theme
  has_one :language, :through => :theme
  has_many :words
  has_many :documents
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :description, :image, :language_id, :name, :name_original

  validates :name, :uniqueness => true
  belongs_to :language
  has_many :subthemes
  has_many :words, :through => :subtheme
  has_many :documents
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :audio, :description, :image, :language_id, :pdf, :subtheme_id, :text_english, :text_image, :text_original

  validates :text_english, :uniqueness => true
  belongs_to :subtheme
  has_one :theme, :through => :subtheme
  has_one :language, :through => :subtheme

  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/languages_controller.rb
class LanguagesController < InheritedResources::Base
end

app/controllers/subthemes_controller.rb
class SubthemesController < InheritedResources::Base
end

app/controllers/themes_controller.rb
class ThemesController < InheritedResources::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/subthemes_helper.rb
module SubthemesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_original %><br />
    <%= f.text_field :name_original %>
  </div>
  <div class="field">
    <%= f.label :name_english %><br />
    <%= f.text_field :name_english %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= language.description %></td>
    <td><%= link_to 'Show', language %></td>
    <td><%= link_to 'Edit', edit_language_path(language) %></td>
    <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
          <div class="large-12 columns">

            <div class="panel">
              <div class="row">
                <div class="large-6 columns">
                  <h4 class="hide-for-small"><%= @language.name %><br/>
                    <span class="subheader"><%= @language.name_original %></span>
                  </h4>
                </div>
              </div>
            </div>

          </div>
</div>

<div class="row">    
    
    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <!-- <div class="large-9 push-3 columns"> -->
    <div class="large-9 push-3 columns">
      
      <!-- <h3><%= @language.name %><small><i><%= @language.name_original %></i></small></h3> -->
      
      <div class="row">
        <div id="slider">
        	<!-- <img src="http://placehold.it/1000x400&text=[ img 1 ]" /> -->
        	<!-- Vimeo Vid -->
        	<div class="flex-video widescreen vimeo">
            <iframe src="http://player.vimeo.com/video/46110750?title=0&amp;byline=0&amp;portrait=0" width="400" height="225" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
          </div>
          <hr />
        </div>
      </div>

      <p>
      	Some info or video...

      	Bacon ipsum dolor sit amet salami ham hock biltong ball tip drumstick sirloin pancetta meatball short loin. Venison tail chuck pork chop, andouille ball tip beef ribs flank boudin bacon. Salami andouille pork belly short ribs flank cow. Salami sirloin turkey kielbasa. Sausage venison pork loin leberkas chuck short loin, cow ham prosciutto pastrami jowl. Ham hock jerky tri-tip, fatback hamburger shoulder swine pancetta ground round. Tri-tip prosciutto meatball turkey, brisket spare ribs shankle chuck cow chicken ham hock boudin meatloaf jowl.</p>
 
      <p>Ground round pastrami pork loin tenderloin jerky. Jerky spare ribs biltong, ham hock ham capicola pork. Jerky turducken pork, meatloaf sausage capicola swine corned beef turkey short loin. Tongue prosciutto pork loin, ground round spare ribs venison kielbasa strip steak.</p>
 
      <p>Hamburger bresaola turkey t-bone, leberkas salami pork chop ham hock beef ribs. Rump biltong meatball venison, short ribs pork loin shank shankle corned beef beef. Cow salami jowl short loin hamburger fatback. Short ribs pork belly shoulder pastrami drumstick salami corned beef ham hock bresaola. Swine filet mignon cow sausage ball tip. Cow ribeye ground round, sausage pork loin pig beef ball tip turkey boudin.</p>
 
      <p>Prosciutto ball tip filet mignon andouille frankfurter chicken rump sausage meatball. Filet mignon meatloaf ground round andouille ham hock pork. Bresaola short loin meatball chuck hamburger pig. Turkey venison chuck, tongue fatback tail swine jerky corned beef shank kielbasa prosciutto ribeye ham tri-tip. Rump bacon pork belly meatloaf shoulder short loin meatball kielbasa pork loin tongue bresaola brisket corned beef jowl prosciutto. Beef ribs shankle short ribs pork belly corned beef fatback pork chop tongue biltong boudin strip steak sirloin meatloaf pancetta.</p>
            
    </div>
    
    
    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="large-3 pull-9 columns">
      <h5>Themes</h5>
      <ul class="side-nav">
        <% @language.themes.each do |t| %>
          <li><%= link_to t.name, theme_path(t)%></li>
        <% end %>
      </ul>
      
      <!-- <p><img src="http://placehold.it/320x240&text=Image" /></p> -->
        
    </div>
    
  </div>
  

app/views/layouts/_breadcrumb.html.erb
<% if params[:controller] == 'languages' %>
	<% language = Language.find(params[:id]) %>
	<%= link_to language.name, language %>
<% elsif params[:controller] == 'themes' %>
	<% theme = Theme.find(params[:id]) %>
	<%= link_to theme.language.name, theme.language %> > <%= link_to theme.name, theme %>
<% elsif params[:controller] == 'subthemes' %>
	<% subtheme = Subtheme.find(params[:id]) %>
	<%= link_to subtheme.language.name, subtheme.language %> > <%= link_to subtheme.theme.name, subtheme.theme %> > <%= link_to subtheme.name, subtheme %>
<% elsif params[:controller] == 'words' %>
	<% word = Word.find(params[:id]) %>
	<%= link_to word.language.name, word.language %> > <%= link_to word.theme.name, word.theme %> > <%= link_to word.subtheme.name, word.subtheme %> > <%= link_to word.text_original, word %>
<% end %>

app/views/layouts/_side_bar.html.erb
<!-- This is source ordered to be pulled to the left on larger screens -->

<!-- <div class="large-3 pull-9 columns"> -->
	<!-- <ul class="side-nav">
		<% Language.order(:name).each do |l| %>
			
			<% if controller_name.classify == 'Language' and @language == l %>
				<li class='active'><%= link_to l.name, language_path(l) %></li>
			<% elsif controller_name.classify == 'Theme' and @theme.language == l %>
				<li class='active'><%= link_to l.name, language_path(l) %></li>
			<% elsif controller_name.classify == 'Subtheme' and @subtheme.language == l %>
				<li class='active'><%= link_to l.name, language_path(l) %></li>
			<% else %>
				<li><%= link_to l.name, language_path(l) %></li>
			<% end %>
		<% end %> -->
		<!-- <li class="active"><a href="#">Link 1</a></li>
		<li><a href="#">Link 2</a></li>
		<li class="divider"></li>
		<li><a href="#">Link 3</a></li>
		<li><a href="#">Link 4</a></li>	 -->
	</ul> 
<!-- </div> -->

<!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="large-3 pull-9 columns">
        
      <ul class="side-nav">
        <li><a href="#">Section 1</a></li>
        <li><a href="#">Section 2</a></li>
        <li><a href="#">Section 3</a></li>
        <li><a href="#">Section 4</a></li>
        <li><a href="#">Section 5</a></li>
        <li><a href="#">Section 6</a></li>
      </ul>
      
      <!-- <p><img src="http://placehold.it/320x240&text=Ad" /></p> -->
        
    </div>

app/views/layouts/_top_bar.html.erb
<!-- <nav class="top-bar">
    <ul class="title-area" width="400px">
      
      <li class="name">
      	<h1 style='float:left'><img src="http://www.sfslanguages.com/wp-content/themes/monochrome/img/logo.gif" width="50px" height="50px"/></h1>
        <h5>
			by Matt Schartow
        </h5>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
 
    <section class="top-bar-section">
      
      <ul class="right">
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#">Languages</a>
          <ul class="dropdown">
            <% Language.all.each do |l| %>
              <li><%= link_to l.name, language_path(l) %></li>
            <% end %>
          </ul>
        </li>
        <li class="divider"></li>
        <li><a href="#">About</a></li>
        <li class="divider"></li>
        <li><a href="#">Schools</a></li>
        <li class="divider"></li>
        <li><a href="#">Foundations</a></li>
      </ul>
    </section>
  </nav>
   -->


  <!-- Header and Nav From Template Below -->
  
  <div class="row">
    <div class="large-3 columns">
      <h1><img src="http://www.sfslanguages.com/wp-content/themes/monochrome/img/logo.gif" width="50px" height="50px"/></h1>
    </div>
    <div class="large-9 columns">
      <ul class="inline-list right">
        <li><%= link_to 'Spanish', language_path(Language.find_by_name('Spanish')) %></li>
        <li><a href="#">Section 2</a></li>
        <li><a href="#">Section 3</a></li>
        <li><a href="#">Section 4</a></li>
      </ul>
    </div>
  </div>
  
  <!-- End Header and Nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
	<title><%= content_for?(:title) ? yield(:title) : "SFS Languages by Matt Schartow" %></title>
  	<%= javascript_include_tag "application" %>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
  	<%= csrf_meta_tags %>
</head>
<body>

  <!-- Nav Topbar -->
  <%= render '/layouts/top_bar' %>
  <div class="row">
    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 columns">
      <%= render '/layouts/breadcrumb' %>
    	<%= yield %>
    </div>
    <!-- Nav Sidebar -->
  	<%#= render 'layouts/side_bar' %>
  </div>
    
  <!-- Footer -->
  
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright SFS Languages 2013</p>
        </div>
        <!-- <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Section 1</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
          </ul>
        </div> -->
      </div>
    </div> 
  </footer>
</body>
</html>

app/views/subthemes/_form.html.erb
<%= form_for(@subtheme) do |f| %>
  <% if @subtheme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtheme.errors.count, "error") %> prohibited this subtheme from being saved:</h2>

      <ul>
      <% @subtheme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br />
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :theme_id %><br />
    <%= f.number_field :theme_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subthemes/edit.html.erb
<h1>Editing subtheme</h1>

<%= render 'form' %>

<%= link_to 'Show', @subtheme %> |
<%= link_to 'Back', subthemes_path %>

app/views/subthemes/index.html.erb
<h1>Listing subthemes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Video url</th>
    <th>Theme</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subthemes.each do |subtheme| %>
  <tr>
    <td><%= subtheme.name %></td>
    <td><%= subtheme.description %></td>
    <td><%= subtheme.image %></td>
    <td><%= subtheme.video_url %></td>
    <td><%= subtheme.theme_id %></td>
    <td><%= link_to 'Show', subtheme %></td>
    <td><%= link_to 'Edit', edit_subtheme_path(subtheme) %></td>
    <td><%= link_to 'Destroy', subtheme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subtheme', new_subtheme_path %>

app/views/subthemes/new.html.erb
<h1>New subtheme</h1>

<%= render 'form' %>

<%= link_to 'Back', subthemes_path %>

app/views/subthemes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
          <div class="large-12 columns">

            <div class="panel" style="padding-top:.5em;padding-bottom:.5em;">
              <div class="row">
                <div class="large-6 columns">
                  <h4 class="hide-for-small"><%= @subtheme.name %><br/>
                    <span class="subheader"><%= @subtheme.description %></span>
                  </h4>
                </div>
              
                <div class="large-6 columns right" style="text-align:right;">
                  <ul style="list-style:none;float:right;margin-top:10px;margin-bottom:0;">
                  <% @subtheme.documents.each do |d| %>
                    <li style="float:left;margin-right:5px;"><%= link_to d.description, d.url, :class => "small button" %></li>
                  <% end %>
                  </ul>
                </div>
              </div>
            </div>

          </div>
</div>
          
<div class="row">
          <div class="large-3 columns">
            <ul style="list-style:none;">
              <% @subtheme.words.each do |w| %>
                <li><%= link_to w.text_english, word_path(w) %></li>
              <% end %>
            </ul>
          </div>

          <div class="large-6 columns">
            <img src="<%= @subtheme.image %>"><br>
          </div>
</div>

app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
  <% if @theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
      <% @theme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.number_field :language_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<h1>Listing themes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @themes.each do |theme| %>
  <tr>
    <td><%= theme.name %></td>
    <td><%= theme.description %></td>
    <td><%= theme.image %></td>
    <td><%= theme.language_id %></td>
    <td><%= link_to 'Show', theme %></td>
    <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
    <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New theme</h1>

<%= render 'form' %>

<%= link_to 'Back', themes_path %>

app/views/themes/old_show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
 
          <div class="large-6 columns">
 
            <h3 class="show-for-small"><%= @theme.name %><hr/></h3>
 
            <div class="panel">
              <h4 class="hide-for-small"><%= @theme.name %><hr/></h4>
              <h5 class="subheader"><%= @theme.description %></h5>
              <ul style="list-style:none;margin-bottom:0;">
              <% @theme.documents.each do |d| %>
                <li><%= link_to d.description, d.url, :class => "small button" %></li>
              <% end %>
              </ul>
            </div>
 
          <div class="row">
            <% @theme.subthemes.each do |s| %>
              <div class="large-6 small-6 columns">
                <div class="panel">
                  <h5><%= s.name %></h5>
                <h6 class="subheader"><%= s.description %></h6>
                <%= link_to 'Start!', subtheme_path(s), :class => "small button" %>
                </div>
              </div>
            <% end %>
              <!-- <div class="large-6 small-6 columns">
                <div class="panel">
                  <h5>Subtheme</h5>
                <h6 class="subheader">Praesent placerat dui tincidunt elit suscipit sed.</h6>
                <a href="#" class="small button">Start!</a>
                </div>
              </div> -->
          </div>
          <!-- <p>
            <b>Download the Flashcard and Worksheet PDFs</b>
            <ul style="list-style:none;margin-bottom:0;">
            <% @theme.documents.each do |d| %>
              <li style="float:left;margin-right:5px;"><%= link_to d.description, d.url, :class => "small button" %></li>
            <% end %>
            </ul>
          </p> -->
          </div>

          <div class="large-6 columns">
 
            <img src="<%= @theme.image %>"><br>
 
          </div>
        </div>
 
 
 
      <!-- End Header Content -->
 
 
      <!-- Search Bar -->
 
        <!-- <div class="row">
 
          <div class="large-12 columns">
            <div class="radius panel">
 
            <form>
              <div class="row collapse">
 
                <div class="large-10 small-8 columns">
                  <input type="text" />
                </div>
 
                <div class="large-2 small-3 columns">
                  <a href="#" class="postfix button expand">Search</a>
                </div>
 
              </div>
            </form>
 
          </div>
          </div>
 
        </div> -->
 
      <!-- End Search Bar -->
 
 
      <!-- Thumbnails -->
 
        <!-- <div class="row">
 
          <div class="large-12 show-for-small columns">
          <h3>Header</h3><hr>
        </div>
 
          <div class="large-3 small-6 columns">
            <img src="http://placehold.it/500x500&text=Word">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>
 
          <div class="large-3 small-6 columns">
            <img src="http://placehold.it/500x500&text=Word">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>
 
          <div class="large-3 small-6 columns">
            <img src="http://placehold.it/500x500&text=Word">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>
 
          <div class="large-3 small-6 columns">
            <img src="http://placehold.it/500x500&text=Word">
            <div class="panel">
              <p>Description</p>
            </div>
          </div>
 
        </div> -->
 
      <!-- End Thumbnails -->

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
          <div class="large-12 columns">

            <div class="panel" style="padding-top:.5em;padding-bottom:.5em;">
              <div class="row">
                <div class="large-6 columns">
                  <h4 class="hide-for-small"><%= @theme.name %> | <%= @theme.name_original %><br/>
                    <span class="subheader"><%= @theme.description %></span>
                  </h4>
                </div>

                <div class="large-6 columns right" style="text-align:right;">
                  <ul style="list-style:none;float:right;margin-top:10px;margin-bottom:0;">
                    <% @theme.documents.each do |d| %>
                      <li><%= link_to d.description, d.url, :class => "small button" %></li>
                    <% end %>
                  </ul>
                </div>

              </div>
            </div>

          </div>
</div>

<div class="row">
 
          <div class="large-6 columns">
            <div class="row">
              <div class="columns">
              <% @theme.subthemes.each do |s| %>
                  <div class="panel">
                      <!-- Theme image -->
                    <div style="float:right;">
                      <%= image_tag @theme.image, :size => '100x100' %>
                    </div>
                    
                    <h5><%= s.name %></h5>
                    <h6 class="subheader"><%= s.description %></h6>
                    <%= link_to 'Start!', subtheme_path(s), :class => "small button" %>

                  </div>
              <% end %>
              </div>
            </div>
          </div>

          <div class="large-6 columns">
            <img src="<%= @theme.image %>"><br>
          </div>
        </div>
 
 
 
      <!-- End Header Content -->
      

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text_image %><br />
    <%= f.text_field :text_image %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :audio %><br />
    <%= f.text_field :audio %>
  </div>
  <div class="field">
    <%= f.label :pdf %><br />
    <%= f.text_field :pdf %>
  </div>
  <div class="field">
    <%= f.label :subtheme_id %><br />
    <%= f.number_field :subtheme_id %>
  </div>
  <div class="field">
    <%= f.label :language_id %><br />
    <%= f.number_field :language_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Description</th>
    <th>Text image</th>
    <th>Image</th>
    <th>Audio</th>
    <th>Pdf</th>
    <th>Subtheme</th>
    <th>Language</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.text %></td>
    <td><%= word.description %></td>
    <td><%= word.text_image %></td>
    <td><%= word.image %></td>
    <td><%= word.audio %></td>
    <td><%= word.pdf %></td>
    <td><%= word.subtheme_id %></td>
    <td><%= word.language_id %></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>